server:
  port: 8086
spring:
  application:
    name: system-service-provider
  main:
    allow-bean-definition-overriding: true
#数据库连接，应用名称以及文件上传设置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-wz9d3uq2rn35r0p6m.mysql.rds.aliyuncs.com:3306/jxc-cloud?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: weiweijixie
    password: WeiWei2019
  redis:
    database: 0
    host: 172.18.10.7
    port: 6379
    password: gongyou2018
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 10000ms
  #rabbitMq的相关配置
  rabbitmq:
    host: 120.79.145.29
    port: 5672
    username: gongyou
    password: gongyou2019
#服务注册中心配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://120.79.145.29:8081/eureka/
#声明Feign的 hystrix支持,如果设置为true，则断路器备用方法将不起作用，默认为false
feign:
     hystrix:
         enabled: true
#hystrix的超时时间
hystrix:
    command:
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 9000
#ribbon的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

#mybatis的配置
mybatis:
  type-aliases-package: com.weiwei.jixieche.bean
  mapper-locations: classpath:mybatis/*.xml,classpath:mybatis/*/*.xml

#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#android下载地址
android:
  downloadUrlOwner: http://app.vvjx.cn/pro/mechanicalsowner.apk
  downloadUrlTenantry: http://app.vvjx.cn/pro/mechanicalsuser.apk
  downloadUrlOwnerTest: http://app.vvjx.cn/ceshi/apk/mechanicalsuser.apk
  downloadUrlTenantryTest: http://app.vvjx.cn/ceshi/apk/mechanicalsuser.apk

#日志记录设置
logging:
  file: /www/wwwlogs/springcloud/systemProvider/yytn.log
  level:
       com:
           weiwei:
                    jixieche: trace
       root: warn